### ISSUE TITLE
[Suggestion] SEO

### ISSUE THREAD

**Issue by TurkeyHawk** [jdm-contrib/justdelete.me#100]
I dunno, all search results and articles forward to [http://backgroundchecks.org/justdeleteme/](http://backgroundchecks.org/justdeleteme/) and not [http://justdeleteme.xyz](http://justdeleteme.xyz) Maybe we can some some SEO? I'm no expert, but I think the second one should be a little more promoted.

**Comment by Nightfirecat** [comment]
http://justdeleteme.xyz has only recently been created, and will likely take a long time to reach greater prominence as the original http://justdelete.me (which now redirects to the first link you posted) is older and more well-known.
