### ISSUE TITLE
last.fm should have "difficulty: impossible"

### ISSUE THREAD

**Issue by sknorr** [jdm-contrib/justdelete.me#12]
Quoting from the last.fm account settings page linked to from your site:

> Close account
> 
> This will deactivate your Last.fm user account, so your user page will no longer be shown on the site.

I just checked and you can indeed reactivate the account at a later time, with all user data intact.

(originally reported as https://github.com/justdeleteme/justdelete.me/issues/723)

**Comment by tupaschoal** [comment]
Thanks for reporting sknorr!
