### ISSUE TITLE
Detach repo

### ISSUE THREAD

**Issue by rugk** [jdm-contrib/justdelete.me#13]
Can you please detach this repo from the not maintained fork?

You can this either [do it manually](https://www.quora.com/Git-revision-control-How-can-one-detach-a-forked-project-in-GitHub#ld_fjxjzo_52503) or (which I recommend) just contact the GitHub support to do it for you.

This…
1. shows that this is a real maintained project and not just a repo of someone who (once) made a pull request
2. linking to the original repo on every page does not make sense anymore as it has been discontinued/is not maintained anymore and you…
3. can (and IMHO should) still link to the original repo/website/author/… for crediting them, but you can do so in better ways (in the Readme, wiki or so)
4. allows searching in this repo on GitHub and
5. it just looks much nicer

**Comment by tupaschoal** [comment]
That's a great idea, I thought it would be more bureaucratic. I did keep the crediting to the authors everywhere, including the LICENSE, do you feel it should be on any other place?

**Comment by rugk** [comment]
I think that's enough… :smiley:

**Comment by tupaschoal** [comment]
Great, we are looking into it as we speak (:

**Comment by PyroSamurai** [comment]
Taken care of :)
