### ISSUE TITLE
Firefox extension

### ISSUE THREAD

**Issue by rugk** [jdm-contrib/justdelete.me#15]
If the Chrome extension is a WebExtension you should quite easily be able to port it to Firefox.
Also the source code of the extension should be in the `jdm-contrib` organisation.

**Comment by tupaschoal** [comment]
I haven't tested, but do you know if the Chrome extension still works? I was just wondering because it looks like it hasn't been updated for a long time.

**Comment by rugk** [comment]
I have not tested it either.

**Comment by tupaschoal** [comment]
I found a firefox extension [here](https://github.com/alaouy/justdelete.me-firefox-addon). Will try testing it, as well as the chrome extension later to see if both still work. Maybe we can convince those guys to hand over the repos to the jdm-contrib organization (:

**Comment by rugk** [comment]
And both seem to be WebExtensions, which is good – as these can be made to work both in Chrome and Firefox (and soon other browsers likely too).

**Comment by tupaschoal** [comment]
I've tested both and they seem to work fine, though they are pulling data from the unmaintained repo.

I've opened issues on both ([Chrome](https://github.com/MikeRogers0/justdelete.me-chrome-extension/issues/2) & [Firefox](https://github.com/alaouy/justdelete.me-firefox-addon/issues/1)) to see if they would be willing to hand the repos over to our organization.

**Comment by tupaschoal** [comment]
The firefox extension is now under our organization, thanks to @alaouy !

I'll see what can be done with it as soon as I can.

**Comment by PyroSamurai** [comment]
Complete

**Comment by artivilla** [comment]
Any updates on the chrome extension? Also, why not just become a collaborator on that project instead and maintain one repo. Doing a quick google search, it seems to get all the leads and it's easier for people looking to contribute.

**Comment by PyroSamurai** [comment]
Neither are being updated or maintained. Both of the original owners have push access to repos, though. We are focusing on improving the website itself at the moment. Not sure what your search terms are but the popularity of one extension over another is a moot point because no development is being done on either. This issue would have been better placed on the chrome extension repo, by the way.

Anyways, feel free to PR on the chrome extension repo if you are interested in contributing to it.

**Comment by artivilla** [comment]
Sorry for the confusion. So updates to this repo with new websites and their delete setups will be reflected in the chrome extension? If so I can contribute here.

**Comment by PyroSamurai** [comment]
If development ever starts again with the chrome extension, yes. It is just a medium which pulls info from the website.
