### ISSUE TITLE
Add Conte.it to site.json

### ISSUE THREAD

**Issue by FrancescoPWC** [jdm-contrib/justdelete.me#153]
[sites.zip](https://github.com/jdm-contrib/justdelete.me/files/1487855/sites.zip)

Hello to all,
I wonder if the Justdeleteme database can be upgraded.
I've updated sites.json file, attached to .zip, adding Conte.it (http://conte.it/).
I have completed all fields of interest by entering the proper notes.

Below the upgraded code in the .json file:

`{
        "name": "Conte.it",
        "url": "http://www.conte.it/privacy-unsubscribe/",
        "difficulty": "easy",
        "notes": "Fill out the form to request cancellation from Conte.it's insurance services.",
        "notes_it": "Compila il form per richiedere la cancellazione dai servizi assicurativi di Conte.it",
        "domains": [
            "conte.it"
        ]
	},`

Waiting for your answer I hope
Good day

**Comment by Nightfirecat** [comment]
I'd advise you [fork this repository](https://help.github.com/articles/fork-a-repo/) and [submit a pull request](https://help.github.com/articles/about-pull-requests/) with these changes. If you're not confident in doing that, I can create a branch in my repository with these changes and open a pull request from it for you instead.

**Comment by FrancescoPWC** [comment]
Hello Nightfirecat,

thanks for your answer. I would be grateful if you opened the pull request for me to insert into the Justdeleteme directory the website  Conte.it.

Thank you

**Comment by Nightfirecat** [comment]
Sure, I'll go ahead and do that for this entry.

**Comment by FrancescoPWC** [comment]
Hi Nightfirecat,

thank you very much for your help and your availability.

Francesco
