### ISSUE TITLE
Add editorconfig

### ISSUE THREAD

**Issue by rugk** [jdm-contrib/justdelete.me#16]
If you add an [editorconfig](http://editorconfig.org/) file you can easily make sure contributors choose the right indentation and similar things. They can choose from a variety of [editor plugins](http://editorconfig.org/#download) and it is even supported by GitHub by default.

**Comment by tupaschoal** [comment]
Sounds really nice, I'll take a look at it later today, thanks!

**Comment by tupaschoal** [comment]
Done @rugk , thank you for your suggestion :)
