### ISSUE TITLE
https://www.upwork.com/

### ISSUE THREAD

**Issue by ThreaT** [jdm-contrib/justdelete.me#18]

**Comment by neeklamy** [comment]
You’re suggesting Upwork should be added to JDM?

It looks like this is probably an ‘easy’, although it depends upon whether contracts and so on are open or not and that any money has been withdrawn ([Upwork - Close my account](https://support.upwork.com/hc/en-us/articles/211067588-Close-my-account)).

**Comment by PyroSamurai** [comment]
@ThreaT please reply, we cannot read your mind.

**Comment by ashtonhogan** [comment]
@PyroSamurai yes, obviously it needs to be added, what else???

**Comment by tupaschoal** [comment]
@ashtonhogan the problem is that he didn't state the difficulty :)

**Comment by tupaschoal** [comment]
Closing issue for lack of response/information.
