### ISSUE TITLE
Add separate optional "email subject" and "email body" fields

### ISSUE THREAD

**Issue by Nightfirecat** [jdm-contrib/justdelete.me#180]
This is an issue for sites which expect account deletion request emails to be formatted in a certain way. This is already an issue for [Zynga](http://justdeleteme.xyz/#zynga), at minimum. (I believe some other entries mention specific verbiage to use in contact emails as well)

**Comment by tupaschoal** [comment]
Sounds doable, but I wonder how many people will know how to use them

**Comment by Nightfirecat** [comment]
It would admittedly be a low-use feature, but currently there's no way to provide an alternative subject/body for the email link.

**Comment by tupaschoal** [comment]
I'm ok with the idea, if you're up for implementing it.
