### ISSUE TITLE
Fix NPM warnings wherever possible

### ISSUE THREAD

**Issue by Nightfirecat** [jdm-contrib/justdelete.me#194]
As part of testing for #193, I did a clean install of the npm packages for this project and got the following output:

```
npm WARN deprecated gulp-util@2.2.20: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated swig@1.4.2: This package is no longer maintained
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated natives@1.1.3: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN justdeleteme@1.0.0 No repository field.
npm WARN justdeleteme@1.0.0 No license field.

added 469 packages in 21.973s
```

We should be able to ideally fix a number of these warnings (use something besides `swig` as it is no longer maintained, replace `gulp-util`?, add repository/license fields, etc.)

**Comment by green-leader** [comment]
I've never really used node but I've got experience working with a number of things. So this seems like it could be something somewhat simple. However, I need a little assistance. 

How would I do a clean install of the packages for the project to get the output? I can run npm install once to get the output but I can't seem to find out how to get the warning output again without removing the entire justdelete.me folder and redoing a clone.

**Comment by Nightfirecat** [comment]
Just remove your `node_modules` directory and re-run `npm install`. That's where all the packages are installed, so clearing them out forces npm to re-install them all.

**Comment by green-leader** [comment]
Aha. Splendid.

**Comment by green-leader** [comment]
I started working on this. Managed to code away from the dependency on gulp-swig by replacing it with gulp-nunjuck. However, it created two more warnings focusing on an optional dependency that only works for macOS. Largely it can probably be ignored.

Started working on another dependency and I found a few problems.
[https://pastebin.com/raw/Qq9MP78f](https://pastebin.com/raw/Qq9MP78f)

That's a log file of doing a check on all of the dependencies. It seems that it's a rabbit hole of depreciations. The two biggest culprits being gulp, and gulp-swig.

I can do my pull request replacing gulp-swig but I'm not sure about how to proceed otherwise. Might be a little over my head to do anything more.

**Comment by Nightfirecat** [comment]
That's fine for now, I appreciate the help. Ultimately, we'll need to upgrade gulp to v`^4.0.0`, which I plan to work on after merging #193. (I'll do that this weekend assuming nobody reviews it by then) If you think your branch is worth PRing, I'd be happy to take a look at it. Even if not, it might be of use to reference when working on addressing the other warnings.
