### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by z5Q46L6bSY1W** [jdm-contrib/justdelete.me#22]
Betterment.com

**Comment by z5Q46L6bSY1W** [comment]
Pro tip: as of today, you can't truly delete an account, only "close" it and still login. The name on the account cannot be changed. Better not to sign up at all.

**Comment by tupaschoal** [comment]
Is there a link to where you can closethe account @z5Q46L6bSY1W ?

**Comment by yoursoftwarebug** [comment]
https://www.betterment.com/
