### ISSUE TITLE
Links in notes

### ISSUE THREAD

**Issue by rugk** [jdm-contrib/justdelete.me#27]
After adding Threema in https://github.com/jdm-contrib/justdelete.me/pull/14 I just saw that [the links in the description](https://jdm-contrib.github.io/justdelete.me/#threema) are not parsed/clickable…

I think you should parse them or is one supposed to use HTML in the notes in the JSON?

**Comment by tupaschoal** [comment]
I actually never thought about this, it is definitely not common to have additional links on the notes. I'm open to suggestions :)

**Comment by rugk** [comment]
As you see they are needed sometimes. So what do you think would be best thing? Just auto-link them, allow HTML or maybe use markdown or so?
Auto-linking would have the disadvantage that you cannot specify a [different text](https://example.com) for a link, but have to include the whole link.

**Comment by Nightfirecat** [comment]
Perhaps this should be covered the same way email/domains are covered?

```
{
    "links": [
        "example.com",
        "another.example.com"
    ],
    // ...
}
```

**Comment by Nightfirecat** [comment]
That said, I think this shouldn't be needed in most cases... In this case, the notes could probably be written better with the fact that the first of the two links is already provided.

**Comment by rugk** [comment]
Yes, but as you see in this example there are many ways/fallbacks, which cover different situations.

**Comment by Nightfirecat** [comment]
In thinking about this for a little while, I wonder if the simplest solution would be to allow HTML in `notes` (perhaps a subset of tags for ease of mind, specifically allowing `<a>`) and specify clear guidelines on how that should be applied in our contributing guide. That affords us the flexibility of adding links that we can control the text of, in cases where we don't want to display the full link URL. Ultimately, no matter what implementation we choose to address this issue, we can generally rest easy knowing that we have full control of changes to sites.json, meaning that there's little worry about potential XSS or otherwise malicious HTML.

**Comment by tupaschoal** [comment]
I'm not sure the pros supersede the cons here, not escaping some of these characters might make the page look messy in some places that we'll never see, I guess.

I have no suggestion on how to overcome this, though ):

**Comment by PyroSamurai** [comment]
I know that Firefox atleast can tell the difference between a link and text if you highlight it. I'm guessing other browsers have a similar ability. All I have to do is double-click to highlight a link, then right-click and choose go to link. Not really feeling any pain from the current method.

My real question is "By disabling the autoescape, does it cause unforeseen problems with other text?"
Either way, like Tulio, I have no suggestions to resolve any of the problems, atm.

**Comment by Nightfirecat** [comment]
As far as I can tell, the page still renders fine even without escaping the characters mentioned, despite it not being correct HTML. I just wouldn't want to rely on that being true in other browsers.
I'll think on this a while and see if I can come up with anything better.

**Comment by Nightfirecat** [comment]
As far as I can tell, the page still renders fine even without escaping the characters mentioned, despite it not being correct HTML. I just wouldn't want to rely on that being true in other browsers.
I'll think on this a while and see if I can come up with anything better.
