### ISSUE TITLE
Revive justdelete.me

### ISSUE THREAD

**Issue by tupaschoal** [jdm-contrib/justdelete.me#4]
As discussed on [this issue](https://github.com/justdeleteme/justdelete.me/issues/731) on the original repository, JDM has been abandoned and wasn't being properly kept. A bunch of us want to keep it alive, so the goal is to slowly migrate people to access it here.

I've updated the website to remove all the phishy information and added some CI tools to keep it healthy, you're welcome to contribute :)

**Comment by PyroSamurai** [comment]
Excellent, l suppose I should add myself to the team as well. I want to update the Dwolla information. Since nobody has made PR for it yet it seems to okay to push a commit for it. By the way I can also go set up a freenode IRC channel for the project if you would like or whatever everybody's preferred chat platform is (I use telegram and IRC mostly)

**Comment by tupaschoal** [comment]
It's been long since I used IRC, but I wouldn't mind if you prefer.

I commented on the first issue and PR page there to draw people here. Also requested access to the owner ( @PyroSamurai ) for @jdm-contrib/contributors to be added to Travis-CI

**Comment by PyroSamurai** [comment]
Okay, I went and granted Travis-CI app access. I honestly would prefer to use Telegram if we could. IRC is kinda of hard to maintain a backlog on what was said while you were away unless you have a server client like I do. It is better used as a help channel or lounge. Do you have a telegram client/account? Btw we already have people coming in an starting issues and PRs, awesome.

**Comment by tupaschoal** [comment]
hahahaha gotta keep the guys motivated 👍 

Telegram it is then, how do I join the channel without disclosing my info here? 😨

**Comment by PyroSamurai** [comment]
how about I disclose mine instead and you can add me to your friend list and we'll go from there? my username is Pyrosamurai, you may need to use the @ symbol.

**Comment by PyroSamurai** [comment]
@neeklamy will you also join the Telegram group channel? just message me on telegram on I will add you to it.

**Comment by tupaschoal** [comment]
Well, seems like it is working, so I am closing the issue :)
