### ISSUE TITLE
Hosting suggestion

### ISSUE THREAD

**Issue by yoursoftwarebug** [jdm-contrib/justdelete.me#47]
You can use Surge instead of using this loooong URL; https://jdm-contrib.github.io/justdelete.me/

e.g., https://justdeleteme.surge.sh

**Comment by tupaschoal** [comment]
Thanks for your suggestion @yoursoftwarebug, but at this time we don't have a concern with short domain names. We don't expect people to type the website from memory, I think they'll come from Google :)
