### ISSUE TITLE
OpenDNS now allows easy deletion

### ISSUE THREAD

**Issue by polyzen** [jdm-contrib/justdelete.me#5]
From the main settings page.

(Just for reference: justdeleteme/justdelete.me/issues/691)

**Comment by tupaschoal** [comment]
@polyzen , care to elaborate on why it is easy now? if there is a link on the settings page or similar. I searched and only found people telling about opening tickets.

**Comment by polyzen** [comment]
Can't remember the details exactly. At the time of opening the ticket, there was a button or link in their main settings to delete your account.

**Comment by tupaschoal** [comment]
Ok thanks @polyzen !
