### ISSUE TITLE
Change "Paypal" classification

### ISSUE THREAD

**Issue by yoursoftwarebug** [jdm-contrib/justdelete.me#54]
It should be "impossible to delete", because Paypal keep your information even you close your account.

Step to confirm:
1. Close your account. (several years ago & recently, 2 samples)
2. Create new account and try to add a credit card to it.
3. You can't do it because Paypal won't let you add same card number on different account[1]
4. Contact support by phone. They will tell you about your previous account information, such as email address and full credit card details.

They are NOT deleting anything.

[1] https://www.paypal-community.com/t5/Account-balance-Archive/My-credit-card-is-used-on-another-account/td-p/179030 and more.

**Comment by tupaschoal** [comment]
Thanks @yoursoftwarebug !
