### ISSUE TITLE
2 suggestions

### ISSUE THREAD

**Issue by yoursoftwarebug** [jdm-contrib/justdelete.me#55]
1. *.nexusmods.com/
Site: https://forums.nexusmods.com/ ,  http|https://www.nexusmods.com/
Classification: Impossible
User have to post a message to close the account. Not "delete". This means they keep your information
from email address to IP address, and your posts.
https://forums.nexusmods.com/index.php?/topic/5416300-account-closure-requests/

2. https://www.darkcreations.org/
Classification: Impossible
They clearly states they never delete user's account for ANY reason.
https://www.darkcreations.org/forums/forum/20-information-support/

**Comment by PyroSamurai** [comment]
@yoursoftwarebug Is there any reason to include the dark creations' site if they clearly state that they won't delete your account. I feel jdm is for those that fall in a gray area or hard to find or deceptive.

**Comment by yoursoftwarebug** [comment]
@PyroSamurai Do people read TOS before register to any website? Most people don't. Take a look at these 2 forum posts. As you can see, some people didn't notice that(because they don't read). I think JDM should add all websites. JDM Firefox/Chrome Addon could be a database of websites.

**Comment by yoursoftwarebug** [comment]
If you try to register new account, there's no mention for "delete account is prohibited". Only generic "I agree to TOS" checkbox.

https://www.darkcreations.org/forums/topic/10134-please-delete-my-account/
https://www.darkcreations.org/forums/topic/11452-could-you-please-delete-this-account/

**Comment by PyroSamurai** [comment]
@yoursoftwarebug I see. Okay that would definitely fall in the gray area. One of the devs will make the final decision, though, so you will need to wait a little longer. Thank you for your continued help.

**Comment by tupaschoal** [comment]
´Done, thanks for reporting :)
