### ISSUE TITLE
Rename suggestion: "Mozilla Persona" to "Mozilla/Firefox"

### ISSUE THREAD

**Issue by yoursoftwarebug** [jdm-contrib/justdelete.me#56]
Because when I tried it, I have to register firefox.com first.
After I got firefox.com account, I was able to create mozilla.org account.

(and the deletion step was easy. just suggesting a title rename)

**Comment by yoursoftwarebug** [comment]
https://addons.mozilla.org/en-US/firefox/
https://oauth.accounts.firefox.com/
https://accounts.firefox.com/oauth/signin...

**Comment by tupaschoal** [comment]
I actually removed it, because the service was shut down.
