### ISSUE TITLE
Add "Mozilla/Firefox"

### ISSUE THREAD

**Issue by ghost** [jdm-contrib/justdelete.me#60]
https://github.com/jdm-contrib/justdelete.me/commit/ce5c1e1849a493fdb5cd80963bd755580f3e3a5a
https://github.com/jdm-contrib/justdelete.me/issues/56

User have to register their account to do review, add new addon, and so on.

https://addons.mozilla.org/en-US/firefox/ <--- click SignIn link(top banner)
https://oauth.accounts.firefox.com/
https://accounts.firefox.com/oauth/signin...

**Comment by tupaschoal** [comment]
Done on #56
