### ISSUE TITLE
PCPartPicker.com should be Easy

### ISSUE THREAD

**Issue by TraumaD** [jdm-contrib/justdelete.me#64]
PcPartPicker.com now has an option under account settings for deleting accounts.

**Comment by Nightfirecat** [comment]
Do you have a link to the settings page?

**Comment by tupaschoal** [comment]
Nice to know about it, if you can provide the link to the settings page, that would be great :)

**Comment by TraumaD** [comment]
https://pcpartpicker.com/user/"username"/preferences/

![screenshot from 2017-05-11 21 23 50](https://cloud.githubusercontent.com/assets/10608836/25979871/9f9fb380-3690-11e7-9f58-927fe91d2f90.png)

**Comment by tupaschoal** [comment]
Hmm, that's no good then. Thanks for the quick answer!
