### ISSUE TITLE
"About" header link does nothing in Firefox 53.0.2

### ISSUE THREAD

**Issue by Nightfirecat** [jdm-contrib/justdelete.me#68]

**Comment by tupaschoal** [comment]
Really? For me it scrolls to the bottom of the page. What are you seeing?

**Comment by Nightfirecat** [comment]
Updated title since it seems to work fine in Chrome, but not Firefox.

**Comment by tupaschoal** [comment]
Weird, it does work on Chrome and Edge, but not Firefox.

**Comment by Nightfirecat** [comment]
I'll take a look at this after my search bar updates since that sounds like it ought to be an easy fix, whatever it is.

That said, I've said the same about cross-browser weirdness before while diving into endless rabbit-holes of confused developers, so I'll just make sure to comment back here later once I take a crack at it.

**Comment by Nightfirecat** [comment]
Didn't manage to dig much up tonight... Will do some more thorough debugging in FF/Chrome tomorrow to see if I can pinpoint the difference.
