### ISSUE TITLE
Search bar issues

### ISSUE THREAD

**Issue by Nightfirecat** [jdm-contrib/justdelete.me#69]
Borrowing this from the source repo's issue list:

> Every time I type a character in the main search box, the URL fragment identifier (the part after the #) is updated to match the contents of the box. It happens even if I type very quickly. I find it pretty annoying, since it creates tons of history entries and makes the "back" button useless. It also causes missed keys when I type too quickly. It would be nice if the URL were only updated once the user stops typing.
>
> In case it's relevant, I tested this with Firefox 43.0 on Ubuntu 14.04.

EDIT: (collapsing comments into one checklist)

So actually there's a bunch of search bar issues...

- [x] Each `keyup` event triggers a hash change where it need not do that
- [ ] ~If you trigger a page update from the full list of sites (eg. from a blank search bar type one letter), it's possible to lose some inputs while the page updates to remove all non-applicable sites. (type "Uber" really fast and you'll end up with something like "Uer" or "Ub" in the search bar)~  
 (mostly a non-issue after the hash update timer implementation)
- [x] Hash/filter don't update when cutting or pasting via right-click
- [x] Spaces become %20 after hash update

**Comment by Nightfirecat** [comment]
So actually there's a bunch of search bar issues...

* Fast searches have some characters overwritten. (type "Uber" really fast and you'll end up with only some of the characters)
* Hash/filter don't update when cutting or pasting via right-click
* Spaces become `%20` after hash update

**Comment by Nightfirecat** [comment]
FYI I'm looking into each of these and hope to have a PR opened to address them tonight.

**Comment by tupaschoal** [comment]
Great! I wanted to address them, but hadn't had the time yet.
