### ISSUE TITLE
Suggestion: Move "Contributing" section of README.md to CONTRIBUTING.md

### ISSUE THREAD

**Issue by Nightfirecat** [jdm-contrib/justdelete.me#72]
https://github.com/blog/1184-contributing-guidelines

See examples:
* [Cockatrice](/Cockatrice/Cockatrice)
* [OBS Studio](/jp9000/obs-studio)

**Comment by tupaschoal** [comment]
Nice suggestion and thanks for the link!

**Comment by Nightfirecat** [comment]
@tupaschoal Actually, one other thing I was sort of wondering about... Would you prefer PRs that update `sites.json` also build and commit their changes? I know you do periodically rev these in master to incorporate changes over time, but I'm just curious on your feelings on if the submitter did it themselves for their incremental change.

**Comment by tupaschoal** [comment]
I don't mind updating them @Nightfirecat , most people do the editing within GitHub itself and don't have a proper environment set up for doing both.
