### ISSUE TITLE
New branding

### ISSUE THREAD

**Issue by will-stone** [jdm-contrib/justdelete.me#82]
May I say, I'm glad this lives on. Such a shame somebody bought the project and has just left it to wilt. With that in mind, it'd be great to get this rebranded and going again. For that you need a domain. I'd like to suggest: pleasedelete.me If you like it, buy it quick before someone holds it to ransom over you.

**Comment by PyroSamurai** [comment]
We appreciate the sentiment but I believe answer will be similar to the one on [this issue](https://github.com/jdm-contrib/justdelete.me/issues/47).

**Comment by will-stone** [comment]
The answer there is to leave discovery to a google search. If that is to be the case, it at least needs rebranding, otherwise people will always end up back at the original.

**Comment by will-stone** [comment]
Also there's so many links / social accounts on the site that end up back at the original. Do you need a site maintainer? I'm happy to go through and update it but I would insist on a rebrand.
