### ISSUE TITLE
Repo Stargazers

### ISSUE THREAD

**Issue by PyroSamurai** [jdm-contrib/justdelete.me#86]
If you have been tagged in this post, it is because you have starred the original JustDeleteMe repo.
The original repo is now defunct and no longer maintained so we the jdm-contrib group have forked it.
We intend to maintain and continue to improve the site for the foreseeable future.
So this why you have been tagged. We ask that you put your support behind us like you did the original so that this app can continue to help and support society at large.

An easy way to show your support is to **star** our repository, submit a pull request, and/or bring an issue to our attention. Thank you for taking the time to read this post.

**Comment by PyroSamurai** [comment]
@andypiper, @JackWH, @cem2ran, @codeThatThinks, @localhorst, @hanigamal, @garrickvanburen, @mattbing, @jarrodldavis, @SiGhTfOrbACQ, @olivalcf, @vijayganduri, @Gerst20051, @LabLayers, @kirkgleffe, @yaph, @GreyBurkart, @webhat, @softvar, @wernersmit, @reimersjan, @MikeDrum, @nancym, @bluetidepro, @Xeoncross, @MikeRogers0, @shuber, @costypetrisor, @ca, @patcon, @sweinberg, @jayvansantos, @bamos, @dfeies, @sesh, @lkydaniel, @seiji, @kevinmrose, @calvinf, @metecik, @dewski, @saji89, @Shoozza, @sathvikp, @hayatoc, @alixaxel, @spanners, @adv0r, @rosswickman, @paccator

**Comment by PyroSamurai** [comment]
@fakelbst, @buzzb0x, @Domon, @irazasyed, @engelju, @gundamew, @599316527, @vivekrp, @vocksel, @MarkBennett, @anhncs, @umaar, @sodevious, @cesarferreira, @LeoColomb, @abiczo, @ELLIOTTCABLE, @od3n, @Doppp, @caseyg, @sbacelic, @robinflyhigh, @sebclick, @gladson, @MChorfa, @yamen, @amitbindal, @akkatracker, @pyprism, @nsina, @jab416171, @lornix, @artemharutyunyan, @alfredbuehler, @stefaneyr, @MiroHibler, @maninhat, @mateioprea, @raik, @mauris, @xPaw, @borfast, @hiikuna, @yogamaterials, @Vaess, @ashking, @vecio, @jbfink, @urre, @eimann

**Comment by PyroSamurai** [comment]
@RJacksonm1, @jefftriplett, @PiranhaGeorge, @CentaurWarchief, @deanpcmad, @Ganonmaster, @domProjects, @zygote, @liruqi, @rajdeep26, @mohitjain, @tantantheman, @waako, @MarceI, @PedroFelipe, @spinsch, @AntoineTurmel, @Abdouye, @freyk, @yizeng, @seyedi, @miql, @codyphobe, @sidwubf, @ukoms, @dot, @sophy, @bastibeckr, @codehype, @paniejakubie, @oumu, @FLasH3r, @ahmedmuslim, @muescha, @MostafaGazar, @ConnorKrammer, @devnall, @bstillman, @ALCEUAGNOLIN, @puikinsh, @skopp, @LaserLock, @balexandre, @lsky, @hoangtx, @atsjj, @codykrieger, @JeffersonBe, @mosaiclife, @kristenmills

**Comment by PyroSamurai** [comment]
@anggiaj, @shalotelli, @Braunson, @The2rB, @avignat, @todeveni, @bgruszka, @thiagokimo, @savage69kr, @andyliu, @LeoWinterDE, @DomenicF, @burningtree, @kvz, @pixelandpen, @mfauveau, @3alil, @baitouwei, @valessiobrito, @seventyeight, @abluescarab, @rafalosinski, @danharper, @BitJackson, @nickmccurdy, @dincho, @alexduros, @filipeoliveiraa, @crootof, @cactus, @tgarrey, @lnsoso, @LorenzoRogai, @stechico, @wikichen, @morozd, @GloverDonovan, @chrisbgp, @Max-Github, @vitorhsb, @em-, @karlozm, @petermikitsh, @neato404, @abishekrsrikaanth, @Kudu, @dvb, @trdlo, @JordanMussi, @mhaidarh

**Comment by PyroSamurai** [comment]
@skrobola, @peter-mauritius, @sub, @docimou, @ThaDafinser, @BuZzi, @joejollands, @garmjs, @lborgav, @jbmusso, @swadhinbharat, @djekl, @caffeinewriter, @cdnuzzo, @twhitacre, @NicholasModesto, @jgrevich, @LostWarrior, @zero2999, @crewshin, @huanghua581, @m4rc, @vBm, @manishk3008, @4michaelcoleman, @joshua, @kevingimbel, @LukyVj, @bethlevene, @Thennis, @romaricdrigon, @scratcher28, @iStenoxx, @giangnb, @bogtan, @fredrikekelund, @Haxker, @JasonPKaplan, @RobertAlan, @praveenvvstgy, @lexx27, @markwu, @matthieu-martin, @DmitrySandalov, @HackBug, @checkraiser, @AlSquire, @mustafamsy, @schmurfy, @hasandz

**Comment by ELLIOTTCABLE** [comment]
This is extremely fucking rude, please stop.

**Comment by PyroSamurai** [comment]
@wmatyskiewicz, @madcoda, @HAE, @robertcedwards, @tnamigata, @ToBeReplaced, @galaxy001, @hakoerber, @laurengalanter, @sgnl02, @bodia-uz, @lboynton, @db80, @dmyers, @TheBeardedLlama, @boardstretcher, @aychtang, @dionysia, @sirwolfgang, @jlouros, @paultreny, @marciotoledo, @mwalien, @ntadashis, @Strubbl, @briandaviddavidson, @macx, @svaksha, @wktk, @notatestuser, @opexxx, @alexanderlperez, @Ingarqisrael, @roks0n, @Bagata, @kranux, @janmyler, @vonbrian, @enko, @thadbryson, @denji, @afc163, @popomore, @radum, @exexzian, @zanetaylor, @ffflorian, @Zekah, @mglowacki100, @lukehan

**Comment by PyroSamurai** [comment]
@simon-andrews, @sharmapradeep, @bartwr, @senthilnayagam, @aaronraimist, @cheeaun, @dqian, @ogt, @ocram, @AbhiAgarwal, @floydchen, @goyalankit, @html5cat, @gdi2290, @fosskers, @vsviridov, @bronfman, @cknadler, @jhm9318, @xiaxiaoyu1988, @dotpot, @grootknol, @nsmeta, @Bambofy, @ybbarng, @thethomaseffect, @JamieH, @exAspArk, @dufferzafar, @joniah, @dideler, @Den3er, @hustcer, @snkreg, @dorentus, @vohof, @PDXIII, @haomingz, @andreasolund, @tru2dagame, @bnb, @mygoare, @ddliu, @mcnkldzyn, @LarryBattle, @mdtareque, @bidpro, @sananth12, @AmaanC, @kametic

**Comment by PyroSamurai** [comment]
@lx4r, @gcq, @deepflame, @Reakiva, @MHM5000, @rchupp, @razanbilwani, @htmlproit, @Stjohndeakins, @xndr1313, @rimenes, @sgsheg, @cwpedersen, @chibicode, @camilohe, @sgb-io, @nderimmorina, @NotBobTheBuilder, @esfilho, @codedaiquiri, @jadedgnome, @noahfrederick, @fb, @glendc1, @christopheschwyzer, @shanshanyang, @hexagoon, @rindeal, @Ashenmaster, @prodigeni, @danmorrison, @VonJagdstrumel, @vasiljevski, @joakimbertil, @PGMY, @oXnMe, @edvardio, @mgafner, @amdest, @Otherworldman, @yesmeck, @technommy, @lewisgoddard, @shsu, @ijd, @fharbe, @djkmiles, @jbinto, @prestonporter, @wiederspielwert

**Comment by PyroSamurai** [comment]
@vterron, @Fuhrmann, @lexbi, @an-dev, @ynasser, @mikehhodgson, @blurkness, @danbender, @dougaitken, @leovbranco, @Code0987, @Konkrad, @sniperwolf, @Zianwar, @rich86, @JT5D, @0unit, @cwtong, @GabrielGil, @tamimibrahim, @edagarli, @victorialo, @keinkurt, @zaork, @forabi, @elboletaire, @DerZyklop, @aneeshmg, @arpitmaheshwari, @tiemay, @web-xaser, @ed-flanagan, @uschek, @msGenDev, @mesutcan, @timothyclifford, @Jerzerak, @ibatullin, @diimpp, @jettify, @412andrewmortimer, @frederickf, @mathieumg, @samcome, @tsudoko, @ylovesy, @guberm, @cxdy, @jaepage, @ScreapDK

**Comment by PyroSamurai** [comment]
@ikirker, @Turbo87, @timelf123, @gary-rafferty, @jakecleary, @takforsnakken, @rwanyoike, @piagomez, @kbohinski, @StarZ3r0, @jscinoz, @mandlapower, @LKNNKL, @hewigovens, @Selat, @looping, @Abirdcfly, @laomo, @shanzi, @mthli, @handaoliang, @Jankst, @Witcher42, @Amztion, @kimmobrunfeldt, @fangmobile, @schlos, @fffonion, @rishirdua, @Akturk, @plu, @datamuc, @ichigotake, @abhinav4848, @ppweek, @karolw, @rwenz3l, @larquin, @callmehiphop, @DanOksnevad, @lllllllllllllllllllllllllllllllllllllll, @SportyHacker, @autos, @faustvault, @astridliu, @johndelanetaylor, @callmecavs, @Steriotis, @yukaibu, @unaizalakain

**Comment by PyroSamurai** [comment]
@Couto, @bright-star, @FFAxKenny, @i02sopop, @trietptm, @otherjustin, @xuncheng, @muhasturk, @yaronyosef, @shingwasix, @wlkr, @rndm-stranger, @AdamRA, @walidsa3d, @flyinggoatman, @zafarella, @garrettw, @ShubhamBadal, @tolbiac110, @vinkla, @usmanakram232, @isakib, @richrad, @azaleamollis, @Guts, @gnu-user, @casidiablo, @virtual-tdf, @calazans10, @MattiSG, @kcparashar, @rensanning, @diegombeltran, @patela29, @anEffingChamp, @jmingov, @jomo, @jayay, @stephtmartin, @isaplan, @Falkirks, @tuankiet65, @bradenbru, @fnkr, @Gedankenleser, @analog-nico, @denniskupec, @aspyatkin, @honorablesquid, @axilleas

**Comment by PyroSamurai** [comment]
@zaxad23, @xyNNN, @pminnieur, @h4cc, @gausby, @kumy, @asaaki, @raphink, @amandasullivan, @StupeFat, @underscorejho, @Nezteb, @KevinPayravi, @jivoi, @AlJohri, @kimar, @SteGriff, @TheKatastrophe, @RyuzakiKK, @kaveet, @hopechow, @ThomasPe, @hoangthienan, @RyannosaurusRex, @sahle123, @kanpeki, @PGMacDesign, @xetch, @BinotaLIU, @ohrie, @angelabier1, @adamgross42, @christopherturner, @GenPage, @Chris1221, @Visgean, @simison, @gmile, @ckihneman, @Pyker, @Okeanos, @Amorymeltzer, @OVigilante, @tigershen23, @Hauwertlhaufn, @fbstj, @brunocvcunha, @coronin, @andrew, @ahmetabdi

**Comment by PyroSamurai** [comment]
@weiland, @Aurif3x, @jonicious, @raumzeit77, @isn0gud, @hmunkey, @vlall, @EHLOVader, @physicalit, @karume, @jhwohlgemuth, @schnittchen, @FeipingHunag, @abumalick, @eliaskousk, @nelooangeloo, @hoenirvili, @Danghor, @MTuner, @seatsea, @maoabc1818, @nickurt, @kerberle, @jackliusr, @SrcFlux, @lipis, @avinashkoyyana, @libraryman, @hoorace, @JamieCruwys, @compwron, @ryomams, @esnard, @vnbhattarai, @domen111, @jessesquires, @Krashnz, @JoseCage, @xavhan, @lokeshguddu, @matthewhochler, @regalised, @Jennifer29, @dhamaniasad, @dehartmatt, @angusshire, @surikat, @dbkaplun, @joeyespo, @duozmo

**Comment by caffeinewriter** [comment]
What the hell dude? This is very uncool. I will not be starring this on principle. Mass tagging is _SERIOUSLY_ uncool, since it subscribes us to the issue, and we get notified for every. Single. Post.

**Comment by PyroSamurai** [comment]
@RustJason, @jkirsh, @lokcon, @yougeekybastard, @ezekills, @dimitrianoudi, @NuggaN85, @537, @ChuLiJun, @MrOutis, @IAmSaad, @RomFouq, @mkleywegt, @danstewart, @che2, @malte70, @xavierThiago, @quicklyandremember, @igor-toporet, @e-flex, @Danand, @elibing, @hfuCN, @pierreozoux, @EthanVoorhees, @boconnell, @burnash, @m-coding, @karldreher, @Freddynic159, @trsantos, @nicholascgilpin, @chkir, @c0mpiler, @suhithr, @sundarv85, @riqpe, @Tatsh, @MCRrAMKkE4, @aneutron, @valentin-nasta, @raisen, @anschch, @Ashu, @FemiAw, @nmss, @AlekseyLeshko, @thisnamewasnottaken, @mrdulin, @grahamg

**Comment by ELLIOTTCABLE** [comment]
He's deleting comments, @caffeinewriter.

**Comment by PyroSamurai** [comment]
@MaximTerra, @DJHartley, @muratbiskin, @AndyMelendezCuesta, @jpsirois, @koobitor, @Miw0, @wikijm, @geekthattweaks, @nkypy, @diogo-fernan, @vishnoisunny, @myfreeweb, @edorgeville, @yarox, @ltartari, @digitaljhelms, @Jackneill, @m-r-m-s, @DVDAndroid, @mlcdf, @dylmye, @arturparkhisenko, @eby, @joolsie, @jugarendy, @eminarslan, @sirLisko, @samirm, @cm-hugog, @c01o, @Unrepentant-Atheist, @asebak, @chyaohui, @pidupuis, @sterrly, @tpgmartin, @bradhughes, @llllllllx, @miguelarauj1o, @privacytoolsIO, @Rishabh04-02, @Au1st3in, @egeesin, @thiagowfx, @hardieman, @remusa, @quidesign, @AaronBurchfield, @yudhasetiawan

**Comment by PyroSamurai** [comment]
@DeclanEWilliams, @moisesmorillo, @nikeee, @invasioncredible, @lewisje, @milanchheda, @burriep, @derekbtw, @jhermsmeier, @tameraydin, @jozadaquebatista, @Sidneylc, @ADarkHero, @matatk, @MarkWithall, @nschonni, @yashodhank, @cadejscroggins, @SolarPolarMan, @joshuarosato, @dobestan, @maximecorbeau, @minecraftpro941, @KozzyKoder, @faviouz, @euantorano, @emaxi, @Machou, @maggick, @ndarville, @Demwunz, @jens1o, @bokobza, @WingedRat, @bartu, @peterbrinck, @coh7eiqu8thaBu, @Starefossen, @FoxxMD, @sam4jips, @misterch0c, @tqdv, @oscaronv1, @mahinthjoe, @HackerInside0, @daviddarnes, @craigcoles, @CraigChilds94, @chriscoffee, @skadimoolam

**Comment by PyroSamurai** [comment]
@hant0508, @tuefekci, @alandooz, @Raindeer44, @albertdick, @drfunkencluck, @gabrielbarros, @andr-andreev, @sudharshanc, @pinapepina, @mbmccormick, @justintieu, @najibalghaeth, @iampox, @mhrabiee, @SilentSpike, @ThreaT, @emanresusername, @pesca, @mmattioli, @abhishek7, @nhantdn, @Tym17, @glepretre, @Jerome1337, @chaficnajjar, @games647, @d-holbach, @ToniCorinne, @timvisee, @ajkblue, @Brotakuu, @Kn0p3XX, @Adger01, @zfeixiang, @sivartravis, @vensko, @PaulCapestany, @ganlub, @kvartz, @sr093906, @abactel, @rkopylkov, @aberlin, @tasen, @0x2Adr1, @adrientoub, @c0riolis, @Dubrzr, @daniphilia

**Comment by PyroSamurai** [comment]
@Comaxim, @zero-t4, @nebulaeos, @Mylainos, @Faiz7412, @Lukaboot, @theprivileges, @0x1110010, @zhn4, @saamsmith, @jkennethcarino, @liweitianux, @tokumeichan, @joseph-rees, @nikki632, @markblackburn77, @ninjaaa, @baimafeima, @CamTosh, @hant05080, @sudoankit, @katsos, @avanthay, @alisen

**Comment by MattiSG** [comment]
Mass-notifying is an unusual and almost spammy practice. Deleting comments that question it, though, is really bad.

It's great that someone takes over the responsibility of maintaining a useful service, and thanks for doing it @PyroSamurai. But this might not be the best way to ask for support :wink:

**Comment by jens1o** [comment]
Hmm, very bad. But I will support the upcoming maintainer. Thanks in advance!

**Comment by caffeinewriter** [comment]
Going to comment again, since you deleted my last one, but this is 100% not cool. I will not be starring this repository on principle after this. Mass tagging is an annoying practice in any scenario, but particularly bothersome in Github issues. I wish you luck in maintaining JDM, but I can't say I plan on actively supporting this.

**Comment by PyroSamurai** [comment]
It was the most efficient way. I appreciate the support. Please minimize posts though, because I do understand that many do not wish to receive extra notifications even though there is a unsubscribe button.

**Comment by lipis** [comment]
Promoting account deletion by subscribing  hundreds of people  to something that we didn't sign up for.. :(

**Comment by ELLIOTTCABLE** [comment]
You've *already caused* them extra notifications, friendo. (For anybody not previously aware — there's an “unsubscribe” button on the right-hand side of this page; I strongly suggest you use it.)

(I, too, am commenting for the — uh, third, time? Christ, kid.)
