### ISSUE TITLE
[Suggestion] Pull sites.json at runtime with Javascript

### ISSUE THREAD

**Issue by Nightfirecat** [jdm-contrib/justdelete.me#91]
A suggestion to reduce the technology stack here: rather than pre-compiling the HTML with any sites.json or template changes, reduce the page to one file and pull & parse sites.json on site load.

Advantages:

* No need to do `gulp build` for new changes to reflect
  * Reduces number of commits needed for a single change
* Reduces initial page load time

Disadvantages:

* Splits page load into multiple requests; can't necessarily be combined, since this would be an async XHR
* Overall page load time remains roughly equivalent, but site may not be fully usable between initial HTML load and sites.json load. (this can be sidestepped with loading indicators or accounted for in post-XHR processing)

I'm fully open to thoughts and suggestions to this end; I haven't spent any time toward implementing this change, so I'm not too attached to any specific details here.

**Comment by PyroSamurai** [comment]
I'm already working on something like that but not using javascript. Just Jekyll and yaml.
